-- Migration generated from prisma/schema.prisma. Run with: npx prisma migrate deploy
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE "CustomerSegment" AS ENUM ('STANDARD','GROWTH','VIP','ENTERPRISE');
CREATE TYPE "TransactionStatus" AS ENUM ('FAILED','PENDING','SUCCEEDED','REFUNDED');
CREATE TYPE "PaymentMethod" AS ENUM ('CARD','UPI','NETBANKING','WALLET','EMI');
CREATE TYPE "EventType" AS ENUM ('PAYMENT_FAILED','CHECKOUT_ABANDONED','SUBSCRIPTION_PAYMENT_FAILED','INVOICE_OVERDUE');
CREATE TYPE "RecoveryCaseStatus" AS ENUM ('OPEN','ELIGIBLE','PROCESSING','AWAITING_OUTCOME','RECOVERED','FAILED','STOPPED','ESCALATED','RESOLVED');
CREATE TYPE "RiskLevel" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "ActionType" AS ENUM ('RETRY_PAYMENT','CREATE_PAYMENT_LINK','SEND_REMINDER','SEND_RECOVERY_MESSAGE','OFFER_ALTERNATE_METHOD','SCHEDULE_RETRY','MARK_RECOVERY_CAMPAIGN','ESCALATE','STOP');
CREATE TYPE "InterventionStatus" AS ENUM ('PROPOSED','APPROVED','EXECUTING','AWAITING_OUTCOME','SUCCEEDED','FAILED','CANCELLED');
CREATE TYPE "OutcomeType" AS ENUM ('PAYMENT_RECOVERED','PAYMENT_FAILED','PAYMENT_LINK_OPENED','CUSTOMER_ENGAGED','PROMISE_TO_PAY','CUSTOMER_OPTED_OUT');
CREATE TYPE "PolicyDecision" AS ENUM ('ALLOW','WAIT','STOP','ESCALATE','REJECT');
CREATE TYPE "ActorType" AS ENUM ('AI','SYSTEM','HUMAN','PROVIDER');
CREATE TYPE "AuditEventType" AS ENUM ('EVENT_INGESTED','CASE_CREATED','CONTEXT_BUILT','SCORE_CALCULATED','AGENT_DECISION_GENERATED','AGENT_VALIDATION_FAILED','POLICY_EVALUATED','INTERVENTION_CREATED','INTERVENTION_EXECUTED','OUTCOME_RECEIVED','REVENUE_ATTRIBUTED','CASE_STOPPED','CASE_ESCALATED','CASE_RESOLVED');
CREATE TYPE "EscalationPriority" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE "EscalationStatus" AS ENUM ('OPEN','ASSIGNED','RESOLVED','STOPPED');

CREATE TABLE "Merchant" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "defaultCurrency" TEXT NOT NULL DEFAULT 'INR', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Merchant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Customer" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "segment" "CustomerSegment" NOT NULL DEFAULT 'STANDARD', "optedOut" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Customer_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Transaction" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "currency" TEXT NOT NULL, "status" "TransactionStatus" NOT NULL, "paymentMethod" "PaymentMethod" NOT NULL, "failureReason" TEXT, "providerReference" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Subscription" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "currency" TEXT NOT NULL, "status" TEXT NOT NULL, "nextBillingAt" TIMESTAMP(3) NOT NULL, "failureCount" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "amountMinor" BIGINT NOT NULL, "currency" TEXT NOT NULL, "dueDate" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL, "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RevenueEvent" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "type" "EventType" NOT NULL, "sourceId" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL, "payload" JSONB NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "processedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RevenueEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecoveryCase" ("id" TEXT NOT NULL, "reference" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "sourceType" "EventType" NOT NULL, "sourceId" TEXT NOT NULL, "amountAtRiskMinor" BIGINT NOT NULL, "currency" TEXT NOT NULL, "status" "RecoveryCaseStatus" NOT NULL DEFAULT 'OPEN', "riskLevel" "RiskLevel" NOT NULL DEFAULT 'MEDIUM', "diagnosisCategory" TEXT, "diagnosisConfidence" DECIMAL(5,4), "recoveryScore" DECIMAL(5,4), "recommendedAction" "ActionType", "attemptCount" INTEGER NOT NULL DEFAULT 0, "contactCount" INTEGER NOT NULL DEFAULT 0, "nextActionAt" TIMESTAMP(3), "lastContactAt" TIMESTAMP(3), "recoveredAmountMinor" BIGINT NOT NULL DEFAULT 0, "escalatedAt" TIMESTAMP(3), "stoppedAt" TIMESTAMP(3), "stopReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "RecoveryCase_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Intervention" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "recoveryCaseId" TEXT NOT NULL, "actionType" "ActionType" NOT NULL, "status" "InterventionStatus" NOT NULL DEFAULT 'PROPOSED', "reason" TEXT NOT NULL, "expectedRecoveryValueMinor" BIGINT NOT NULL, "expectedProbability" DECIMAL(5,4), "actionSuccessProbability" DECIMAL(5,4), "policyDecision" "PolicyDecision", "policyRule" TEXT, "executedAt" TIMESTAMP(3), "outcomeAt" TIMESTAMP(3), "recoveredAmountMinor" BIGINT NOT NULL DEFAULT 0, "providerReference" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Intervention_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OutcomeEvent" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "recoveryCaseId" TEXT NOT NULL, "interventionId" TEXT, "type" "OutcomeType" NOT NULL, "amountMinor" BIGINT NOT NULL DEFAULT 0, "currency" TEXT NOT NULL, "providerReference" TEXT, "occurredAt" TIMESTAMP(3) NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OutcomeEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Policy" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "name" TEXT NOT NULL, "eventType" "EventType" NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "rulesJson" JSONB NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Policy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Escalation" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "recoveryCaseId" TEXT NOT NULL, "priority" "EscalationPriority" NOT NULL, "reason" TEXT NOT NULL, "status" "EscalationStatus" NOT NULL DEFAULT 'OPEN', "assignedTo" TEXT, "resolvedAt" TIMESTAMP(3), "resolutionNotes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Escalation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "recoveryCaseId" TEXT, "interventionId" TEXT, "traceId" TEXT NOT NULL, "actorType" "ActorType" NOT NULL, "eventType" "AuditEventType" NOT NULL, "decision" TEXT, "reason" TEXT, "policyResult" "PolicyDecision", "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AgentRun" ("id" TEXT NOT NULL, "traceId" TEXT NOT NULL, "merchantId" TEXT NOT NULL, "recoveryCaseId" TEXT NOT NULL, "provider" TEXT NOT NULL, "model" TEXT, "inputContextHash" TEXT, "outputJson" JSONB, "validationStatus" TEXT NOT NULL, "latencyMs" INTEGER, "error" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AgentRun_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Customer_merchantId_email_key" ON "Customer"("merchantId","email");
CREATE UNIQUE INDEX "RevenueEvent_merchantId_idempotencyKey_key" ON "RevenueEvent"("merchantId","idempotencyKey");
CREATE UNIQUE INDEX "RecoveryCase_reference_key" ON "RecoveryCase"("reference");
CREATE UNIQUE INDEX "RecoveryCase_merchantId_sourceType_sourceId_key" ON "RecoveryCase"("merchantId","sourceType","sourceId");
CREATE UNIQUE INDEX "Policy_merchantId_name_version_key" ON "Policy"("merchantId","name","version");
CREATE INDEX "Customer_merchantId_segment_idx" ON "Customer"("merchantId","segment");
CREATE INDEX "Transaction_merchantId_status_idx" ON "Transaction"("merchantId","status");
CREATE INDEX "Transaction_customerId_createdAt_idx" ON "Transaction"("customerId","createdAt");
CREATE INDEX "Subscription_merchantId_status_idx" ON "Subscription"("merchantId","status");
CREATE INDEX "Invoice_merchantId_status_dueDate_idx" ON "Invoice"("merchantId","status","dueDate");
CREATE INDEX "RevenueEvent_merchantId_type_occurredAt_idx" ON "RevenueEvent"("merchantId","type","occurredAt");
CREATE INDEX "RecoveryCase_merchantId_status_idx" ON "RecoveryCase"("merchantId","status");
CREATE INDEX "RecoveryCase_merchantId_nextActionAt_idx" ON "RecoveryCase"("merchantId","nextActionAt");
CREATE INDEX "RecoveryCase_merchantId_riskLevel_idx" ON "RecoveryCase"("merchantId","riskLevel");
CREATE INDEX "Intervention_merchantId_status_idx" ON "Intervention"("merchantId","status");
CREATE INDEX "Intervention_recoveryCaseId_createdAt_idx" ON "Intervention"("recoveryCaseId","createdAt");
CREATE INDEX "OutcomeEvent_merchantId_type_occurredAt_idx" ON "OutcomeEvent"("merchantId","type","occurredAt");
CREATE INDEX "OutcomeEvent_recoveryCaseId_type_idx" ON "OutcomeEvent"("recoveryCaseId","type");
CREATE INDEX "Policy_merchantId_eventType_enabled_idx" ON "Policy"("merchantId","eventType","enabled");
CREATE INDEX "Escalation_merchantId_status_priority_idx" ON "Escalation"("merchantId","status","priority");
CREATE INDEX "AuditLog_merchantId_createdAt_idx" ON "AuditLog"("merchantId","createdAt");
CREATE INDEX "AuditLog_recoveryCaseId_createdAt_idx" ON "AuditLog"("recoveryCaseId","createdAt");
CREATE INDEX "AuditLog_traceId_idx" ON "AuditLog"("traceId");
CREATE INDEX "AgentRun_merchantId_createdAt_idx" ON "AgentRun"("merchantId","createdAt");
CREATE INDEX "AgentRun_recoveryCaseId_createdAt_idx" ON "AgentRun"("recoveryCaseId","createdAt");

ALTER TABLE "Customer" ADD CONSTRAINT "Customer_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RevenueEvent" ADD CONSTRAINT "RevenueEvent_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RevenueEvent" ADD CONSTRAINT "RevenueEvent_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecoveryCase" ADD CONSTRAINT "RecoveryCase_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecoveryCase" ADD CONSTRAINT "RecoveryCase_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Intervention" ADD CONSTRAINT "Intervention_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Intervention" ADD CONSTRAINT "Intervention_recoveryCaseId_fkey" FOREIGN KEY ("recoveryCaseId") REFERENCES "RecoveryCase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OutcomeEvent" ADD CONSTRAINT "OutcomeEvent_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OutcomeEvent" ADD CONSTRAINT "OutcomeEvent_recoveryCaseId_fkey" FOREIGN KEY ("recoveryCaseId") REFERENCES "RecoveryCase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OutcomeEvent" ADD CONSTRAINT "OutcomeEvent_interventionId_fkey" FOREIGN KEY ("interventionId") REFERENCES "Intervention"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Policy" ADD CONSTRAINT "Policy_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Escalation" ADD CONSTRAINT "Escalation_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Escalation" ADD CONSTRAINT "Escalation_recoveryCaseId_fkey" FOREIGN KEY ("recoveryCaseId") REFERENCES "RecoveryCase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_recoveryCaseId_fkey" FOREIGN KEY ("recoveryCaseId") REFERENCES "RecoveryCase"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_interventionId_fkey" FOREIGN KEY ("interventionId") REFERENCES "Intervention"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AgentRun" ADD CONSTRAINT "AgentRun_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AgentRun" ADD CONSTRAINT "AgentRun_recoveryCaseId_fkey" FOREIGN KEY ("recoveryCaseId") REFERENCES "RecoveryCase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
