"use client";
import { useEffect, useState } from "react";
import { dashboardFetch } from "./data";
import { MetricCard } from "./metric-card";
import { formatMinorUnits, formatPercent } from "@/lib/format/money";

type Metrics = { totalRevenueAtRiskMinor: string; eligibleRevenueMinor: string; intervenedRevenueMinor: string; recoveredRevenueMinor: string; pendingRecoveryRevenueMinor: string; recoveryRate: { numeratorMinor: string; denominatorMinor: string; percentage: number }; interventionSuccessRate: { numerator: number; denominator: number; percentage: number }; revenueRiskCases: number; interventions: number; successfulRecoveries: number; stoppedCases: number; escalatedCases: number; escalatedRevenueMinor: string; stoppedRevenueMinor: string };
type Funnel = { stage: string; cases: number; amountMinor: string; conversionPercentage: number | null }[];
type Activity = { id: string; recoveryCaseId?: string; eventType: string; actorType: string; reason?: string; createdAt: string }[];

export function OverviewDashboard() {
  const [metrics, setMetrics] = useState<Metrics | null>(null); const [funnel, setFunnel] = useState<Funnel | null>(null); const [activity, setActivity] = useState<Activity | null>(null); const [error, setError] = useState(false); const [simulationRunning, setSimulationRunning] = useState(false); const [simulationMessage, setSimulationMessage] = useState<string | null>(null);
  const loadDashboard = () => Promise.all([dashboardFetch<Metrics>("/api/dashboard/metrics"), dashboardFetch<Funnel>("/api/dashboard/funnel"), dashboardFetch<Activity>("/api/dashboard/activity?limit=6")]).then(([m, f, a]) => { setMetrics(m); setFunnel(f); setActivity(a); });
  useEffect(() => { loadDashboard().catch(() => setError(true)); }, []);
  async function runSimulation() { setSimulationRunning(true); setSimulationMessage(null); try { const response = await fetch("/api/dashboard/demo/run", { method: "POST", headers: { "x-merchant-id": process.env.NEXT_PUBLIC_DEMO_MERCHANT_ID || "merchant_demo" } }); if (!response.ok) throw new Error(); const body = await response.json() as { data: { status: string } }; setSimulationMessage(body.data.status === "ALREADY_COMPLETED" ? "Demo already completed · no duplicate outcomes created" : "Demo completed · metrics refreshed from persisted outcomes"); await loadDashboard(); } catch { setSimulationMessage("Unable to run demo simulation."); } finally { setSimulationRunning(false); } }
  if (error) return <ErrorState title="Unable to load recovery overview." />;
  if (!metrics || !funnel || !activity) return <LoadingState />;
  return <div className="p-10"><header className="mb-8 flex items-end justify-between"><div><p className="mb-2 text-xs uppercase tracking-[0.2em] text-amber">Revenue Recovery</p><h1 className="text-3xl font-semibold tracking-tight">Autopilot overview</h1><p className="mt-2 text-sm text-muted">Merchant operations · Last 30 days</p></div><div className="flex items-center gap-4"><span className="text-xs text-quiet">Acme Commerce India</span><span className="rounded-md border border-border px-3 py-2 text-sm text-muted">Live data</span><button type="button" onClick={runSimulation} disabled={simulationRunning} className="rounded-md bg-amber px-3 py-2 text-sm font-medium text-ink disabled:cursor-not-allowed disabled:opacity-50">{simulationRunning ? "Running…" : "Run recovery simulation"}</button></div></header>{simulationMessage && <p className="mb-5 rounded-md border border-border bg-surface px-4 py-3 text-sm text-muted">{simulationMessage}</p>}
    <section className="grid grid-cols-4 gap-4"><MetricCard label="Revenue at risk" value={metrics.totalRevenueAtRiskMinor} note={`${metrics.revenueRiskCases.toLocaleString("en-IN")} risk cases`} /><MetricCard label="Revenue recovered" value={metrics.recoveredRevenueMinor} dominant note={`${metrics.successfulRecoveries.toLocaleString("en-IN")} successful recoveries`} /><MetricCard label="Recovery rate" percent={metrics.recoveryRate.percentage} note={`${formatMinorUnits(metrics.recoveryRate.numeratorMinor)} / ${formatMinorUnits(metrics.recoveryRate.denominatorMinor)}`} /><MetricCard label="Interventions" value={metrics.interventions} note={`${formatPercent(metrics.interventionSuccessRate.percentage)} success rate`} /></section>
    <section className="mt-6 grid grid-cols-[1.35fr_1fr] gap-6"><div className="rounded-lg border border-border bg-surface p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">Recovery funnel</h2><p className="mt-1 text-sm text-muted">Current merchant batch progression</p></div><span className="text-xs text-quiet">Amounts in INR</span></div><div className="mt-8 space-y-4">{funnel.map((stage, index) => <div key={stage.stage}><div className="mb-2 flex items-end justify-between"><div><span className={`text-sm font-medium ${stage.stage === "RECOVERED" ? "text-amber" : "text-paper"}`}>{stage.stage.replace("_", " ")}</span><span className="ml-3 text-xs text-quiet">{stage.cases.toLocaleString("en-IN")} cases</span></div><div className={`num text-lg font-semibold ${stage.stage === "RECOVERED" ? "text-amber" : "text-paper"}`}>{formatMinorUnits(stage.amountMinor)}</div></div><div className="h-2 rounded-full bg-elevated"><div className={`h-2 rounded-full ${stage.stage === "RECOVERED" ? "bg-amber" : "bg-info"}`} style={{ width: `${index === 0 ? 100 : Math.min(100, Math.max(2, stage.conversionPercentage ?? 0))}%` }} /></div>{stage.conversionPercentage !== null && <p className="mt-1 text-right text-[11px] text-quiet">{formatPercent(stage.conversionPercentage)} from previous stage</p>}</div>)}</div></div><div className="rounded-lg border border-border bg-surface p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">AI recovery activity</h2><p className="mt-1 text-sm text-muted">Recent system decisions</p></div><span className="h-2 w-2 rounded-full bg-success" /></div><div className="mt-6 divide-y divide-border">{activity.length === 0 ? <p className="py-8 text-sm text-muted">No recovery activity found.</p> : activity.map((item) => <div key={item.id} className="py-4 first:pt-0"><div className="flex items-center justify-between text-[11px] text-quiet"><span>{new Date(item.createdAt).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}</span><span className="uppercase tracking-wider">{item.actorType}</span></div><p className="mt-1 text-sm text-paper">{item.eventType.replaceAll("_", " ")}</p><p className="mt-1 line-clamp-2 text-xs text-muted">{item.reason || "No reason recorded."}</p></div>)}</div></div></section>
    <section className="mt-6 grid grid-cols-4 gap-4"><MiniMetric label="Eligible revenue" value={metrics.eligibleRevenueMinor} /><MiniMetric label="Pending recovery" value={metrics.pendingRecoveryRevenueMinor} /><MiniMetric label="Escalated revenue" value={metrics.escalatedRevenueMinor} /><MiniMetric label="Stopped revenue" value={metrics.stoppedRevenueMinor} /></section>
  </div>;
}
function MiniMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-border bg-surface px-5 py-4"><p className="text-xs text-muted">{label}</p><p className="num mt-2 text-lg font-medium">{formatMinorUnits(value)}</p></div>; }
export function LoadingState() { return <div className="p-10"><div className="h-5 w-32 animate-pulse rounded bg-elevated" /><div className="mt-3 h-9 w-72 animate-pulse rounded bg-elevated" /><div className="mt-10 grid grid-cols-4 gap-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-36 rounded-lg border border-border bg-surface" />)}</div></div>; }
export function ErrorState({ title }: { title: string }) { return <div className="m-10 rounded-lg border border-danger/50 bg-surface p-8"><p className="text-sm font-medium text-danger">{title}</p><p className="mt-2 text-sm text-muted">Check the merchant connection and try again.</p></div>; }
