"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { dashboardFetch } from "@/components/dashboard/data";
import { formatMinorUnits } from "@/lib/format/money";
import { ErrorState, LoadingState } from "@/components/dashboard/overview-dashboard";

type CaseItem = { id: string; merchantId: string; customerId: string; status: string; sourceType: string; amountAtRiskMinor: string; riskLevel: string; diagnosisCategory?: string; recommendedAction?: string; attemptCount: number; recoveredAmountMinor: string };
type CaseResponse = { items: CaseItem[]; total: number; page: number; pageSize: number };
export function CasesPage() { const [result, setResult] = useState<CaseResponse | null>(null); const [error, setError] = useState(false); useEffect(() => { dashboardFetch<CaseResponse>("/api/recovery-cases?page=1&pageSize=50&sortBy=createdAt&sortOrder=desc").then(setResult).catch(() => setError(true)); }, []); if (error) return <ErrorState title="Unable to load revenue-risk cases." />; if (!result) return <LoadingState />; return <div className="p-10"><header className="mb-8 flex items-end justify-between"><div><p className="mb-2 text-xs uppercase tracking-[0.2em] text-amber">Operations</p><h1 className="text-3xl font-semibold">At-risk cases</h1><p className="mt-2 text-sm text-muted">{result.total.toLocaleString("en-IN")} persisted recovery cases</p></div><span className="rounded-md border border-border px-3 py-2 text-xs text-quiet">Merchant batch</span></header><div className="overflow-hidden rounded-lg border border-border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b border-border bg-elevated text-xs uppercase tracking-wider text-quiet"><tr>{["Customer", "Event", "Amount", "Risk", "Diagnosis", "Next action", "Attempts", "Status", "Recovered"].map((heading) => <th key={heading} className="px-4 py-4 font-medium">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{result.items.length === 0 ? <tr><td colSpan={9} className="px-6 py-14 text-center text-muted">No revenue-risk cases found.</td></tr> : result.items.map((item) => <tr key={item.id} className="hover:bg-elevated"><td className="px-4 py-4"><Link href={`/cases/${item.id}`} className="font-medium text-paper hover:text-amber">{item.customerId}</Link><div className="mt-1 text-[11px] text-quiet">{item.id}</div></td><td className="px-4 py-4 text-muted">{item.sourceType.replaceAll("_", " ")}</td><td className="num px-4 py-4 text-paper">{formatMinorUnits(item.amountAtRiskMinor)}</td><td className="px-4 py-4"><StatusLabel value={item.riskLevel} tone={item.riskLevel === "CRITICAL" || item.riskLevel === "HIGH" ? "danger" : "muted"} /></td><td className="px-4 py-4 text-muted">{item.diagnosisCategory || "Not recorded"}</td><td className="px-4 py-4 text-muted">{item.recommendedAction || "Not recorded"}</td><td className="num px-4 py-4 text-muted">{item.attemptCount}</td><td className="px-4 py-4"><StatusLabel value={item.status} tone={item.status === "RECOVERED" ? "success" : item.status === "ESCALATED" ? "warning" : "muted"} /></td><td className="num px-4 py-4 text-paper">{formatMinorUnits(item.recoveredAmountMinor)}</td></tr>)}</tbody></table></div></div>; }
export function StatusLabel({ value, tone = "muted" }: { value: string; tone?: "success" | "danger" | "warning" | "muted" }) { const colors = { success: "text-success border-success/30", danger: "text-danger border-danger/30", warning: "text-warning border-warning/30", muted: "text-muted border-border" }; return <span className={`inline-flex rounded-full border px-2 py-1 text-[10px] font-medium uppercase tracking-wider ${colors[tone]}`}>{value.replaceAll("_", " ")}</span>; }
