"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { dashboardFetch } from "@/components/dashboard/data";
import { formatMinorUnits } from "@/lib/format/money";

type Row = Record<string, unknown>;
const titles: Record<string, { eyebrow: string; description: string }> = { recoveries: { eyebrow: "Performance", description: "Cases with recorded successful payment recovery." }, interventions: { eyebrow: "Execution", description: "Recovery actions selected and executed by the system." }, customers: { eyebrow: "Relationships", description: "Customers represented in the recovery workspace." }, escalations: { eyebrow: "Human review", description: "Cases requiring an operator decision." }, audit: { eyebrow: "Governance", description: "Immutable operational decisions and outcomes." }, policies: { eyebrow: "Controls", description: "Deterministic merchant rules applied before execution." } };
export function OperationsPage({ resource }: { resource: keyof typeof titles }) { const [rows, setRows] = useState<Row[] | null>(null); const [error, setError] = useState(false); useEffect(() => { const endpoint = resource === "audit" ? "/api/audit-logs" : `/api/${resource === "recoveries" ? "recovery-cases?status=RECOVERED" : resource}`; dashboardFetch<Row[] | { items: Row[] }>(endpoint).then((data) => setRows(Array.isArray(data) ? data : data.items)).catch(() => setError(true)); }, [resource]); const meta = titles[resource]; if (error) return <PageFrame eyebrow={meta.eyebrow} title={label(resource)}><Notice tone="danger">Unable to load {label(resource).toLowerCase()}. Check the merchant connection and try again.</Notice></PageFrame>; if (!rows) return <PageFrame eyebrow={meta.eyebrow} title={label(resource)}><div className="h-56 animate-pulse rounded-lg border border-border bg-surface" /></PageFrame>; return <PageFrame eyebrow={meta.eyebrow} title={label(resource)}><p className="mb-5 text-sm text-muted">{meta.description}</p>{rows.length === 0 ? <Notice>No {label(resource).toLowerCase()} found.</Notice> : <div className="overflow-hidden rounded-lg border border-border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b border-border bg-elevated text-xs uppercase tracking-wider text-quiet"><tr>{headers(resource).map((header) => <th key={header} className="px-4 py-4 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((row, index) => <tr key={String(row.id || index)} className="hover:bg-elevated">{cells(resource, row)}</tr>)}</tbody></table></div>}</PageFrame>; }
function PageFrame({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="p-10"><p className="text-xs uppercase tracking-[0.2em] text-amber">{eyebrow}</p><div className="mt-2 flex items-end justify-between"><h1 className="text-3xl font-semibold">{title}</h1><span className="rounded-md border border-border px-3 py-2 text-xs text-quiet">DEMO MODE</span></div><div className="mt-8">{children}</div></div>; }
function Notice({ children, tone = "muted" }: { children: React.ReactNode; tone?: "muted" | "danger" }) { return <div className={`rounded-lg border bg-surface p-8 text-sm ${tone === "danger" ? "border-danger/50 text-danger" : "border-border text-muted"}`}>{children}</div>; }
function label(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
function headers(resource: string) { return resource === "customers" ? ["Customer", "Email", "Segment", "Recovery cases"] : resource === "escalations" ? ["Priority", "Case", "Reason", "Status"] : resource === "audit" ? ["Time", "Event", "Actor", "Reason"] : resource === "policies" ? ["Policy", "Event", "Version", "Status"] : resource === "interventions" ? ["Action", "Case", "Status", "Created"] : ["Case", "Event", "At risk", "Recovered", "Status"]; }
function cells(resource: string, row: Row) { if (resource === "customers") return <><td className="px-4 py-4 text-paper">{String(row.name || row.id)}</td><td className="px-4 py-4 text-muted">{String(row.email || "Hidden")}</td><td className="px-4 py-4 text-muted">{String(row.segment || "—")}</td><td className="num px-4 py-4 text-paper">{String((row._count as Row | undefined)?.recoveryCases || row.caseCount || 0)}</td></>; if (resource === "escalations") return <><td className="px-4 py-4 text-warning">{String(row.priority || "—")}</td><td className="px-4 py-4 text-paper">{String((row.case as Row | undefined)?.reference || (row.recoveryCase as Row | undefined)?.reference || row.recoveryCaseId || "—")}</td><td className="px-4 py-4 text-muted">{String(row.reason || "—")}</td><td className="px-4 py-4 text-muted">{String(row.status || "—")}</td></>; if (resource === "audit") return <><td className="px-4 py-4 text-xs text-quiet">{row.createdAt ? new Date(String(row.createdAt)).toLocaleString("en-IN") : "—"}</td><td className="px-4 py-4 text-paper">{String(row.eventType || "—").replaceAll("_", " ")}</td><td className="px-4 py-4 text-muted">{String(row.actorType || "—")}</td><td className="px-4 py-4 text-muted">{String(row.reason || "—")}</td></>; if (resource === "policies") return <><td className="px-4 py-4 text-paper">{String(row.name || row.id)}</td><td className="px-4 py-4 text-muted">{String(row.eventType || "—").replaceAll("_", " ")}</td><td className="num px-4 py-4 text-muted">{String(row.version || 1)}</td><td className="px-4 py-4 text-success">{row.enabled ? "Enabled" : "Disabled"}</td></>; if (resource === "interventions") return <><td className="px-4 py-4 text-paper">{String(row.actionType || "—").replaceAll("_", " ")}</td><td className="px-4 py-4 text-muted">{String(row.recoveryCaseId || "—")}</td><td className="px-4 py-4 text-muted">{String(row.status || "—")}</td><td className="px-4 py-4 text-xs text-quiet">{row.createdAt ? new Date(String(row.createdAt)).toLocaleString("en-IN") : "—"}</td></>; return <><td className="px-4 py-4"><Link href={`/cases/${row.id}`} className="text-paper hover:text-amber">{String(row.reference || row.id)}</Link></td><td className="px-4 py-4 text-muted">{String(row.sourceType || "—").replaceAll("_", " ")}</td><td className="num px-4 py-4 text-paper">{row.amountAtRiskMinor ? formatMinorUnits(String(row.amountAtRiskMinor)) : "—"}</td><td className="num px-4 py-4 text-success">{row.recoveredAmountMinor ? formatMinorUnits(String(row.recoveredAmountMinor)) : formatMinorUnits(0n)}</td><td className="px-4 py-4 text-muted">{String(row.status || "—")}</td></>; }
