/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { executeRecoveryAction } from "@/lib/actions/executor";
import { executeAgentRecommendation } from "@/lib/actions/orchestration";
import { MockPaymentProvider } from "@/lib/payments/mock";
import type { ActionRepository } from "@/lib/actions/types";
import type { PolicyConfig, RecoveryCaseSnapshot } from "@/lib/recovery/types";

const policy: PolicyConfig = { maxAttempts: 3, maxContacts: 3, cooldownHours: 24, highValueThresholdMinor: 5_000_000n, minimumRecoveryScore: 0.25, afterMaximumAttempts: "STOP", afterMaximumContacts: "STOP", supportedActions: ["RETRY_PAYMENT", "CREATE_PAYMENT_LINK", "SEND_RECOVERY_MESSAGE", "SEND_REMINDER", "SCHEDULE_RETRY", "ESCALATE", "STOP"] };
const base: RecoveryCaseSnapshot = { id: "case-action", merchantId: "merchant-action", customerId: "customer-action", status: "ELIGIBLE", sourceType: "PAYMENT_FAILED", sourceId: "payment-action", amountAtRiskMinor: 499900n, currency: "INR", attemptCount: 0, contactCount: 0, lastContactAt: null, nextActionAt: null, recoveredAmountMinor: 0n, recoveryScore: 0.8, customerOptedOut: false, paymentAlreadySuccessful: false, escalated: false };
function fakeRepository(current: RecoveryCaseSnapshot = { ...base }): ActionRepository & { interventions: Map<string, { id: string; resultJson?: unknown }>; outcomes: unknown[]; audits: unknown[] } { const interventions = new Map<string, { id: string; resultJson?: unknown }>(); const outcomes: unknown[] = []; const audits: unknown[] = []; return { interventions, outcomes, audits, findCase: async (merchantId, caseId) => merchantId === current.merchantId && caseId === current.id ? current : null, findInterventionByIdempotencyKey: async (_merchantId, _caseId, key) => { const item = interventions.get(key); return item?.resultJson ? { id: item.id, resultJson: item.resultJson } : null; }, createIntervention: async (input) => { const item = { id: `intervention-${interventions.size + 1}` }; interventions.set(input.idempotencyKey, item); return item; }, updateInterventionResult: async (id, result) => { for (const item of interventions.values()) if (item.id === id) item.resultJson = result; }, recordOutcome: async (input) => { outcomes.push(input); }, updateCase: async (_merchantId, _caseId, patch) => { Object.assign(current, patch); }, audit: async (input) => { audits.push(input); } }; }
const input = (repository: ActionRepository, action: any, provider = new MockPaymentProvider("SUCCESSFUL_RETRY")) => ({ merchantId: base.merchantId, caseId: base.id, action, policy, repository, paymentProvider: provider, traceId: "trace-action", idempotencyKey: `key-${String(action)}`, now: new Date("2026-01-01T12:00:00Z") });

describe("action executor", () => {
  it("re-evaluates policy, executes retry, records outcome, and attributes recovery", async () => { const repository = fakeRepository(); const result = await executeRecoveryAction(input(repository, "RETRY_PAYMENT")); expect(result.success).toBe(true); expect(result.outcome).toBe("PAYMENT_RECOVERED"); expect(result.amountRecoveredMinor).toBe(499900n); expect(repository.outcomes).toHaveLength(1); expect((repository.findCase as unknown)).toBeDefined(); });
  it("creates payment links without claiming payment recovery", async () => { const repository = fakeRepository(); const result = await executeRecoveryAction(input(repository, "CREATE_PAYMENT_LINK", new MockPaymentProvider("PAYMENT_LINK_CREATED"))); expect(result.outcome).toBe("PAYMENT_LINK_CREATED"); expect(result.amountRecoveredMinor).toBe(0n); expect(repository.outcomes).toHaveLength(1); });
  it("supports deterministic message, reminder, and scheduling actions", async () => { for (const action of ["SEND_RECOVERY_MESSAGE", "SEND_REMINDER", "SCHEDULE_RETRY"] as const) { const repository = fakeRepository(); const result = await executeRecoveryAction(input(repository, action)); expect(result.success).toBe(true); expect(result.provider).toBe("internal"); } });
  it("rejects stopped, recovered, opted-out, cooldown, and limited cases", async () => { for (const current of [{ status: "STOPPED" }, { status: "RECOVERED", paymentAlreadySuccessful: true }, { customerOptedOut: true }, { attemptCount: 3 }, { contactCount: 3 }, { lastContactAt: new Date("2026-01-01T00:00:00Z") }] as Partial<RecoveryCaseSnapshot>[]) { await expect(executeRecoveryAction(input(fakeRepository({ ...base, ...current }), "RETRY_PAYMENT"))).rejects.toThrow(); } });
  it("escalates and stops through controlled state transitions", async () => { const escalated = fakeRepository(); expect((await executeRecoveryAction(input(escalated, "ESCALATE"))).outcome).toBe("CASE_ESCALATED"); const stopped = fakeRepository(); expect((await executeRecoveryAction(input(stopped, "STOP"))).outcome).toBe("CASE_STOPPED"); });
  it("is idempotent and never repeats a side effect", async () => { const repository = fakeRepository(); const first = await executeRecoveryAction(input(repository, "RETRY_PAYMENT")); const second = await executeRecoveryAction(input(repository, "RETRY_PAYMENT")); expect(second.idempotent).toBe(true); expect(repository.outcomes).toHaveLength(1); expect(second.providerReference).toBe(first.providerReference); });
  it("fails safely on provider errors and records an audit event", async () => { const repository = fakeRepository(); await expect(executeRecoveryAction(input(repository, "RETRY_PAYMENT", new MockPaymentProvider("PROVIDER_FAILURE")))).rejects.toThrow(); expect(repository.audits).toHaveLength(1); });
  it("rejects unsupported domain actions", async () => { await expect(executeRecoveryAction(input(fakeRepository(), "OFFER_ALTERNATE_METHOD"))).rejects.toThrow(); });
});

describe("agent to action orchestration", () => {
  it("executes only the validated recommendation after policy authorization", async () => { const repository = fakeRepository(); const agentResult = { context: { merchantId: base.merchantId, caseId: base.id, policy, currentState: base.status } as any, recommendation: { case_id: base.id, diagnosis: { category: "expired_card", confidence: 0.9 }, decision: { action: "retry_payment", reason: "reason", expected_recovery_value_minor: 0n }, next_step: { type: "await_outcome", cooldown_hours: 24 }, escalate: false }, policy: { outcome: "ALLOW", ruleCode: "ACTION_ALLOWED", reason: "allowed" }, traceId: "trace-agent" } as any; const result = await executeAgentRecommendation({ agentResult, repository, paymentProvider: new MockPaymentProvider("SUCCESSFUL_RETRY"), idempotencyKey: "agent-key" }); expect(result.action).toBe("RETRY_PAYMENT"); });
  it("does not execute a failed agent result", async () => { await expect(executeAgentRecommendation({ agentResult: { safeFailure: { code: "TIMEOUT", reason: "timeout" }, traceId: "trace-fail" } as any, repository: fakeRepository(), paymentProvider: new MockPaymentProvider(), idempotencyKey: "failed" })).rejects.toThrow(); });
});
