import { describe, expect, it, vi } from "vitest";
import { buildAgentContext } from "@/lib/agent/context";
import { agentDecisionSchema } from "@/lib/agent/schema";
import { AgentProviderError, DeterministicTestProvider, RetryingAgentProvider } from "@/lib/agent/provider";
import { runRecoveryAgent } from "@/lib/agent/agent";
import type { AgentRunRepository, AgentAuditRepository } from "@/lib/agent/agent";
import type { PolicyConfig, RecoveryCaseSnapshot } from "@/lib/recovery/types";

const policy: PolicyConfig = { maxAttempts: 3, maxContacts: 3, cooldownHours: 24, highValueThresholdMinor: 5_000_000n, minimumRecoveryScore: 0.25, afterMaximumAttempts: "STOP", afterMaximumContacts: "STOP", supportedActions: ["RETRY_PAYMENT", "CREATE_PAYMENT_LINK", "SEND_RECOVERY_MESSAGE", "SEND_REMINDER", "SCHEDULE_RETRY"] };
const recoveryCase: RecoveryCaseSnapshot = { id: "case-agent-1", merchantId: "merchant-1", customerId: "customer-1", status: "ELIGIBLE", sourceType: "PAYMENT_FAILED", sourceId: "payment-1", amountAtRiskMinor: 500000n, currency: "INR", attemptCount: 0, contactCount: 0, lastContactAt: null, nextActionAt: null, recoveredAmountMinor: 0n, recoveryScore: null, customerOptedOut: false, paymentAlreadySuccessful: false, escalated: false };
const contextInput = { recoveryCase, failureReason: "expired_card", customerSegment: "VIP" as const, successfulPaymentCount: 8, failureCount: 1, priorRecoveryOutcomes: ["PAYMENT_FAILED"], previousInterventionCount: 1, scoringInput: { successfulPayments: 8, totalPayments: 9, daysSinceLastSuccessfulPayment: 10, failureRecoverability: 0.9, customerValue: 0.8, engagement: 0.7 }, policy };
function repos() { const runs: unknown[] = []; const audits: unknown[] = []; return { runs, audits, runRepository: { create: vi.fn(async (x) => { runs.push(x); }) } as AgentRunRepository, auditRepository: { create: vi.fn(async (x) => { audits.push(x); }) } as AgentAuditRepository }; }

describe("agent context", () => {
  it("builds minimized context without email, phone, or raw payload", () => { const context = buildAgentContext(contextInput, "trace-1"); expect(context.caseId).toBe(recoveryCase.id); expect(context.amountAtRiskMinor).toBe(500000n); expect(context).not.toHaveProperty("email"); expect(context).not.toHaveProperty("payload"); expect(context.recoveryScore.factors.historicalSuccess).toBeCloseTo(8 / 9); });
});

describe("agent schema and provider", () => {
  it("accepts a valid decision and rejects invalid action/confidence/value/cooldown", () => { const valid = { case_id: "case-agent-1", diagnosis: { category: "expired_card", confidence: 0.9 }, decision: { action: "create_payment_link", reason: "Method-specific failure.", expected_recovery_value_minor: "1000" }, next_step: { type: "await_outcome", cooldown_hours: 24 }, escalate: false }; expect(agentDecisionSchema.parse(valid).decision.expected_recovery_value_minor).toBe(1000n); expect(() => agentDecisionSchema.parse({ ...valid, decision: { ...valid.decision, action: "execute_sql" } })).toThrow(); expect(() => agentDecisionSchema.parse({ ...valid, diagnosis: { ...valid.diagnosis, confidence: 2 } })).toThrow(); expect(() => agentDecisionSchema.parse({ ...valid, decision: { ...valid.decision, expected_recovery_value_minor: -1 } })).toThrow(); expect(() => agentDecisionSchema.parse({ ...valid, next_step: { ...valid.next_step, cooldown_hours: 721 } })).toThrow(); });
  it("returns deterministic decisions without side effects", async () => { const provider = new DeterministicTestProvider(); const first = await provider.generateDecision(buildAgentContext(contextInput, "t")); const second = await provider.generateDecision(buildAgentContext(contextInput, "t")); expect(first).toEqual(second); });
  it("handles provider timeout and retries", async () => { const provider = new RetryingAgentProvider({ providerName: "failing", generateDecision: () => new Promise((_, reject) => setTimeout(() => reject(new AgentProviderError("timeout", "TIMEOUT")), 5)) }, { retries: 1, timeoutMs: 20 }); await expect(provider.generateDecision(buildAgentContext(contextInput, "t"))).rejects.toThrow("timeout"); });
});

describe("agent orchestration", () => {
  it("persists a valid run, recalculates value, and evaluates policy", async () => { const repositories = repos(); const result = await runRecoveryAgent({ context: contextInput, provider: new DeterministicTestProvider(), ...repositories, traceId: "trace-valid", now: new Date("2026-01-01T12:00:00Z") }); expect(result.recommendation).toBeDefined(); expect(result.serverExpectedRecoveryValueMinor).toBe(305784n); expect(result.recommendation?.decision.expected_recovery_value_minor).toBe(0n); expect(result.policy.outcome).toBe("ALLOW"); expect(repositories.runRepository.create).toHaveBeenCalledWith(expect.objectContaining({ validationStatus: "VALID", traceId: "trace-valid" })); });
  it("fails safely on wrong case ID and malformed output", async () => { for (const provider of [{ providerName: "wrong", generateDecision: async () => ({ case_id: "wrong", diagnosis: { category: "unknown", confidence: 0.5 }, decision: { action: "retry_payment", reason: "x", expected_recovery_value_minor: 1 }, next_step: { type: "await_outcome", cooldown_hours: 1 }, escalate: false }) }, { providerName: "malformed", generateDecision: async () => ({ bad: true }) }]) { const repositories = repos(); const result = await runRecoveryAgent({ context: contextInput, provider, ...repositories, traceId: "trace-fail" }); expect(result.safeFailure).toBeDefined(); expect(result.policy.outcome).toBe("REJECT"); expect(repositories.runRepository.create).toHaveBeenCalledWith(expect.objectContaining({ validationStatus: "FAILED" })); } });
  it("returns policy rejection for a valid recommendation", async () => { const repositories = repos(); const result = await runRecoveryAgent({ context: { ...contextInput, policy: { ...policy, supportedActions: ["RETRY_PAYMENT"] } }, provider: new DeterministicTestProvider(), ...repositories, traceId: "trace-reject" }); expect(result.recommendation).toBeDefined(); expect(result.policy.outcome).toBe("REJECT"); expect(result.policy.ruleCode).toBe("UNSUPPORTED_ACTION"); });
  it("escalates a valid recommendation for a high-value case", async () => { const repositories = repos(); const result = await runRecoveryAgent({ context: { ...contextInput, recoveryCase: { ...recoveryCase, amountAtRiskMinor: 5000000n } }, provider: new DeterministicTestProvider(), ...repositories, traceId: "trace-high" }); expect(result.recommendation).toBeDefined(); expect(result.policy.outcome).toBe("ESCALATE"); });
  it("does not produce an actionable recommendation for stopped cases", async () => { const repositories = repos(); const result = await runRecoveryAgent({ context: { ...contextInput, recoveryCase: { ...recoveryCase, status: "STOPPED" } }, provider: new DeterministicTestProvider(), ...repositories, traceId: "trace-stopped" }); expect(result.policy.outcome).toBe("STOP"); });
});
