import { describe, expect, it } from "vitest";
import { aggregateExecutiveMetrics, actualRecoveredByCase } from "@/lib/metrics/aggregation";
import { buildRecoveryFunnel } from "@/lib/metrics/funnel";
import type { MetricCase, MetricIntervention, MetricOutcome } from "@/lib/metrics/types";
const cases: MetricCase[] = [{ id: "a", status: "RECOVERED", amountAtRiskMinor: 1000n }, { id: "b", status: "ELIGIBLE", amountAtRiskMinor: 2000n }, { id: "c", status: "STOPPED", amountAtRiskMinor: 3000n }, { id: "d", status: "ESCALATED", amountAtRiskMinor: 4000n }];
const interventions: MetricIntervention[] = [{ id: "i-a", recoveryCaseId: "a", status: "SUCCEEDED" }, { id: "i-b", recoveryCaseId: "b", status: "AWAITING_OUTCOME" }];
const outcome = (id: string, caseId: string, amountMinor: bigint, type = "PAYMENT_RECOVERED", interventionId: string | null = "i-a"): MetricOutcome => ({ id, recoveryCaseId: caseId, interventionId, type, amountMinor, occurredAt: new Date("2026-01-01") });
describe("metrics aggregation", () => {
  it("counts only successful payment outcomes and caps duplicate recovery", () => { const recovered = actualRecoveredByCase(cases, [outcome("o1", "a", 700n), outcome("o2", "a", 700n), outcome("o3", "a", 50n, "PAYMENT_LINK_CREATED")]); expect(recovered.get("a")).toBe(1000n); expect(recovered.get("b")).toBeUndefined(); });
  it("calculates executive metrics from persisted-like records", () => { const metrics = aggregateExecutiveMetrics(cases, interventions, [outcome("o1", "a", 1000n), outcome("o2", "a", 1n)]); expect(metrics.totalRevenueAtRiskMinor).toBe(10000n); expect(metrics.eligibleRevenueMinor).toBe(3000n); expect(metrics.intervenedRevenueMinor).toBe(3000n); expect(metrics.recoveredRevenueMinor).toBe(1000n); expect(metrics.pendingRecoveryRevenueMinor).toBe(2000n); expect(metrics.recoveryRate.numeratorMinor).toBe(1000n); expect(metrics.recoveryRate.denominatorMinor).toBe(3000n); expect(metrics.recoveryRate.percentage).toBeCloseTo(33.333, 2); expect(metrics.interventionSuccessRate.numerator).toBe(1); expect(metrics.interventionSuccessRate.denominator).toBe(2); expect(metrics.stoppedRevenueMinor).toBe(3000n); expect(metrics.escalatedRevenueMinor).toBe(4000n); });
  it("handles zero denominators", () => { const metrics = aggregateExecutiveMetrics([], [], []); expect(metrics.recoveryRate.percentage).toBe(0); expect(metrics.interventionSuccessRate.percentage).toBe(0); });
  it("handles very large BigInt values", () => { const large = 9_000_000_000_000_000_000n; const metrics = aggregateExecutiveMetrics([{ id: "large", status: "RECOVERED", amountAtRiskMinor: large }], [], [outcome("large-outcome", "large", large)]); expect(metrics.recoveredRevenueMinor).toBe(large); });
});
describe("recovery funnel", () => { it("calculates stage amounts and conversion percentages", () => { const funnel = buildRecoveryFunnel(cases, interventions, [outcome("o1", "a", 1000n)]); expect(funnel.map((stage) => stage.stage)).toEqual(["AT_RISK", "ELIGIBLE", "INTERVENED", "RECOVERED"]); expect(funnel[0].amountMinor).toBe(10000n); expect(funnel[3].amountMinor).toBe(1000n); expect(funnel[3].conversionPercentage).toBeCloseTo(33.333, 2); }); });
